// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjwnekdrtcwpeneoaesh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqd25la2RydGN3cGVuZW9hZXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMTY3MjYsImV4cCI6MjA0OTU5MjcyNn0.ctbDURdtGj7hvQRfx_S1tucNwtThP3zNHXcD5yxCKac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);